//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Авторы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Авторы()
        {
            this.Авторы_книги = new HashSet<Авторы_книги>();
        }
    
        public int Код_Автора { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Примечание { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Авторы_книги> Авторы_книги { get; set; }
    }
}
