//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдача
    {
        public int Номер_Выдачи { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public System.DateTime Дата_Возврата { get; set; }
        public System.DateTime Сдано { get; set; }
        public int Срок { get; set; }
        public Nullable<int> Номер_читательного_билета { get; set; }
        public Nullable<int> Код_книги { get; set; }
        public string Название_книги { get; set; }
    
        public virtual Книги Книги { get; set; }
        public virtual Читатели Читатели { get; set; }
    }
}
